version: '2'
services:
  minifi.dev:
    build:
        context: ./images/DemoAgent
        dockerfile: Dockerfile
    image: jdye64/atlroadshow:DemoAgent
    networks:
     - dev
    hostname: minifi
    domainname: dev
    ports:
     - "8181:8080"
     - "8090:8090"
    links:
     - nifi.dev
  nifi.dev:
    build:
        context: ./images/DemoServer
        dockerfile: Dockerfile
    image: jdye64/atlroadshow:DemoServer
    networks:
     - dev
    hostname: nifi
    domainname: dev
    ports:
     - "8080:8080"
     - "9191:9191"
    links:
     - master0.dev
     - dn0.dev
  postgres.dev:
    image: jdye64/docker-hwx:hdp-postgres-250
    networks:
     - dev
    hostname: postgres
    domainname: dev
  ambari-server.dev:
    image: jdye64/docker-hwx:hdp-ambari-server-250
    networks:
     - dev
    hostname: ambari-server
    domainname: dev
    ports:
     - "8081:8080"
    links:
     - postgres.dev
  master0.dev:
    image: jdye64/docker-hwx:hdp-node-250
    privileged: true
    networks:
     - dev
    hostname: master0
    domainname: dev
    ports:
     # ZooKeeper
     - "2181:2181"
     # HDFS
     - "8020:8020"
     - "9000:9000"
     - "50090:50090"
     # YARN
     - "8088:8088"
     - "8050:8050"
     - "8025:8025"
     - "8030:8030"
     - "8141:8141"
     - "45454:45454"
     - "10200:10200"
     - "8188:8188"
     - "8190:8190"
     - "19888:19888"
     # HiveServer2
     - "10000:10000"
     - "9999:9999"
     - "9933:9933"
     - "10015:10015"
     # HBase
     - "16000:16000"
     - "16010:16010"
     # Storm
     #- "8000:8000"
     - "8744:8744"
     # Oozie
     - "11000:11000"
     - "11443:11443"
     # Knox
     - "8443:8443"
     # Ranger
     - "6080:6080"
     - "6182:6182"
     - "6083:6083"
     - "6183:6183"
     # Grafana
     - "3000:3000"
     # Zeppelin
     - "9995:9995"
     # Kerberos
     #- "88:88"
  dn0.dev:
    image: jdye64/docker-hwx:hdp-node-250
    privileged: true
    networks:
     - dev
    hostname: dn0
    domainname: dev
    ports:
     # HDFS
     - "50070:50070"
     - "50470:50470"
     - "50075:50075"
     - "50475:50475"
     - "50010:50010"
     - "50020:50020"
     - "50030:50030"
     # HBase
     - "16020:16020"
     - "16030:16030"
     # Yarn
     - "45455:45454"
     - "8042:8042"
     # Solr
     - "8983:8983"
     # Kafka
     - "6667:6667"
networks:
  dev:
    driver: bridge